notifications:
  email: false

sudo: false
language: python
python: 3.4
cache: pip

env:
  global:
    - STACK_NAME=sandbox
    - DNS_HOSTNAME=$STACK_NAME-$TRAVIS_BRANCH
    - DNS_DOMAIN=sagebridge.org
    - REPO_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)"

before_install:
  - mkdir ~/.aws
  - echo -e "[default]\nregion=us-east-1" >> ~/.aws/config
  - echo -e "[default]\naws_access_key_id=$SandboxBootstrapUserAccessKeyId\naws_secret_access_key=$SandboxBootstrapUserSecretAccessKeyId" >> ~/.aws/credentials

install:
  - pip install --upgrade awscli

script:
# process local file
#  - aws cloudformation validate-template --template-body file://cf_templates/eb_bridgepf_bootstrap.yml
#  - aws cloudformation validate-template --template-body file://cf_templates/eb_bridgepf.yml

# process files from s3 bucket, required when template files are greater than 50K
# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
  - aws s3 cp cf_templates s3://org-sagebridge-bridgepf-artifacts-sandbox-infra-develop/cf_templates --recursive
  - aws cloudformation validate-template --template-url https://s3.amazonaws.com/org-sagebridge-bridgepf-artifacts-sandbox-infra-develop/cf_templates/eb_bridgepf_bootstrap.yml
  - aws cloudformation validate-template --template-url https://s3.amazonaws.com/org-sagebridge-bridgepf-artifacts-sandbox-infra-develop/cf_templates/eb_bridgepf.yml
  - ./deploy_infra.sh

