notifications:
  email: false

sudo: false
language: python
python: 3.4
cache: pip

env:
  global:
    - STACK_NAME=sandbox
    - DNS_HOSTNAME=$STACK_NAME-$TRAVIS_BRANCH
    - DNS_DOMAIN=sagebridge.org
    - REPO_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)"

before_install:
  - mkdir ~/.aws
  - echo -e "[default]\nregion=us-east-1" >> ~/.aws/config
  - echo -e "[default]\naws_access_key_id=$SandboxBootstrapUserAccessKeyId\naws_secret_access_key=$SandboxBootstrapUserSecretAccessKeyId" >> ~/.aws/credentials

install:
  - pip install --upgrade awscli

script:
  - ./deploy_infra.sh
