notifications:
  email: false

sudo: false
language: python
python: 3.4
cache: pip

before_install:
- mkdir ~/.aws
- echo -e "[default]\nregion=us-east-1" >> ~/.aws/config
- echo -e "[default]\naws_access_key_id=$AwsKey\naws_secret_access_key=$AwsSecretKey" >> ~/.aws/credentials

install:
  - pip install --upgrade awscli

script:
  - aws s3 cp *.yml s3://org-sagebridge-deployment-sandbox-infra-develop
  - aws cloudformation validate-template --template-url https://s3.amazonaws.com/org-sagebridge-deployment-sandbox-infra-develop/eb_app.yml
  - aws cloudformation validate-template --template-url https://s3.amazonaws.com/org-sagebridge-deployment-sandbox-infra-develop/eb_bridgepf.yml
